const express = require('express');
const qdisksController = require('../controllers/qdisksController');

const router = express.Router();

/**
 * @swagger
 * tags:
 *   name: QDisks
 *   description: Manage Linux traffic control qdiscs (CRUD over an abstract store)
 */

/**
 * @swagger
 * components:
 *   schemas:
 *     Qdisc:
 *       type: object
 *       required:
 *         - id
 *         - device
 *         - kind
 *       properties:
 *         id:
 *           type: string
 *           description: Unique identifier for the qdisc configuration
 *         device:
 *           type: string
 *           description: Network device name (e.g., eth0)
 *         parent:
 *           type: string
 *           description: Parent handle (e.g., "root" or "1:")
 *         handle:
 *           type: string
 *           description: Handle identifier (e.g., "1:")
 *         kind:
 *           type: string
 *           description: Qdisc kind (e.g., tbf, fq_codel, fq, pfifo_fast)
 *         params:
 *           type: object
 *           description: Kind-specific parameters
 *       example:
 *         id: "eth0-root-tbf"
 *         device: "eth0"
 *         parent: "root"
 *         handle: "1:"
 *         kind: "tbf"
 *         params:
 *           rate: "10mbit"
 *           burst: "32k"
 *           latency: "400ms"
 */

/**
 * @swagger
 * /api/qdisks:
 *   get:
 *     summary: List qdiscs
 *     tags: [QDisks]
 *     responses:
 *       200:
 *         description: List of qdiscs
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status: { type: string }
 *                 data:
 *                   type: array
 *                   items:
 *                     $ref: '#/components/schemas/Qdisc'
 */
router.get('/', qdisksController.list);

/**
 * @swagger
 * /api/qdisks/{id}:
 *   get:
 *     summary: Get qdisc by id
 *     tags: [QDisks]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *         description: Qdisc id
 *     responses:
 *       200:
 *         description: Qdisc details
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status: { type: string }
 *                 data:
 *                   $ref: '#/components/schemas/Qdisc'
 *       404:
 *         description: Qdisc not found
 */
router.get('/:id', qdisksController.get);

/**
 * @swagger
 * /api/qdisks:
 *   post:
 *     summary: Create qdisc
 *     tags: [QDisks]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [device, kind]
 *             properties:
 *               id:
 *                 type: string
 *                 description: Optional custom id; autogenerated if missing
 *               device:
 *                 type: string
 *               parent:
 *                 type: string
 *               handle:
 *                 type: string
 *               kind:
 *                 type: string
 *                 enum: [tbf, fq_codel, fq, pfifo_fast, cake, htb]
 *               params:
 *                 type: object
 *     responses:
 *       201:
 *         description: Created
 *       400:
 *         description: Validation failed
 *       409:
 *         description: Already exists
 */
router.post('/', qdisksController.create);

/**
 * @swagger
 * /api/qdisks/{id}:
 *   put:
 *     summary: Update qdisc
 *     tags: [QDisks]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               device: { type: string }
 *               parent: { type: string }
 *               handle: { type: string }
 *               kind: { type: string, enum: [tbf, fq_codel, fq, pfifo_fast, cake, htb] }
 *               params: { type: object }
 *     responses:
 *       200:
 *         description: Updated
 *       400:
 *         description: Validation failed
 *       404:
 *         description: Not found
 */
router.put('/:id', qdisksController.update);

/**
 * @swagger
 * /api/qdisks/{id}:
 *   delete:
 *     summary: Delete qdisc
 *     tags: [QDisks]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *     responses:
 *       200:
 *         description: Deleted
 *       404:
 *         description: Not found
 */
router.delete('/:id', qdisksController.remove);

module.exports = router;
